package org.webserver.gui;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.webserver.config.Configuration;
import org.webserver.core.Client;
import org.webserver.dto.ApiConstructor;
import org.webserver.dto.request.LoginRequest;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Base64;
import java.util.Objects;

public class LoginGUI extends JFrame {
    private Client client;

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI(Client client) {
        initComponents();
        this.setVisible(true);
        this.client = client;
        this.setTitle("MyHosting");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        txtUsername = new JTextField();
        txtPassword = new JPasswordField();
        btnLogin = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("Welcome to MyHosting");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        txtUsername.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtPassword.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 342, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtUsername)
                                                        .addComponent(txtPassword, GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))))
                                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUsername, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPassword, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }/// </editor-fold>

    private void txtUsernameActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtPasswordActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnLoginActionPerformed(ActionEvent evt) {
        String username = txtUsername.getText();
        String password = txtPassword.getText();

        if(!Objects.equals(username, "") && !Objects.equals(password, "")){
            ApiConstructor<LoginRequest> apiConstructor = new ApiConstructor<>("login", new LoginRequest(username, password));

            try {
//            Chuyển đổi sang JSON
                ObjectMapper mapper = new ObjectMapper();
                String jsonRequest = mapper.writeValueAsString(apiConstructor);
                client.getOut().write(jsonRequest.getBytes(StandardCharsets.UTF_8));
                client.getOut().flush();

//            RESPONSE
                byte[] buffer = new byte[1024];
                int bytesRead = client.getIn().read(buffer);
                String jsonResponse = new String(buffer, 0, bytesRead, StandardCharsets.UTF_8);
//            JSON => Text
                JsonNode rootNode = mapper.readTree(jsonResponse);
                String message = rootNode.get("message").asText();
                if(Objects.equals(message, "Success")){
                    WebServiceGUI newFrame = new WebServiceGUI(client, username);
                    newFrame.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Login failed!", "Login error", JOptionPane.ERROR_MESSAGE);
                    txtUsername.setText("");
                    txtPassword.setText("");
                }
            } catch (IOException e){
                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Login failed!", "Login error", JOptionPane.ERROR_MESSAGE);
        }
    }




    private void formWindowClosed(WindowEvent evt) {
        // TODO add your handling code here:
    }

    private void formWindowClosing(WindowEvent evt) {
        // TODO add your handling code here:
    }




    // Variables declaration - do not modify
    private JButton btnLogin;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPasswordField txtPassword;
    private JTextField txtUsername;
    // End of variables declaration
}