package org.webserver.gui;

import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.webserver.core.Client;
import org.webserver.dto.ApiConstructor;
import org.webserver.dto.request.ActiveRequest;
import org.webserver.dto.request.LoginRequest;
import org.webserver.dto.request.StopRequest;
import org.webserver.dto.request.WebServiceRequest;
import org.webserver.dto.response.WebServiceResponse;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Objects;

public class WebServiceGUI extends javax.swing.JFrame {
    private Client client;
    private String username;
    private ObjectMapper mapper;
    private String subDomain = "";
    private String status = "";
    private int selectedRowIndex;

    /**
     * Creates new form WebServiceGUI
     */
    public WebServiceGUI(Client client, String username) {
        initComponents();
        this.setVisible(true);
        this.setTitle("MyHosting");
        this.client = client;
        this.username = username;
        this.mapper = new ObjectMapper();
        lbUsername.setText(username.toUpperCase());
        getAllData();
    }

    private void getAllData() {
        ApiConstructor<WebServiceRequest> apiConstructor = new ApiConstructor<>("get all webservices", new WebServiceRequest(username));

        try {
//            Chuyển đổi sang JSON
            String jsonRequest = mapper.writeValueAsString(apiConstructor);
            this.client.getOut().write(jsonRequest.getBytes(StandardCharsets.UTF_8));
            this.client.getOut().flush();


//            RESPONSE
            byte[] buffer = new byte[1024];
            int bytesRead = this.client.getIn().read(buffer);
            String jsonResponse = new String(buffer, 0, bytesRead, StandardCharsets.UTF_8);
            System.out.println(jsonResponse);

//          Chuyển đổi JSON sang ApiConstructor<List<WebServiceResponse>>
            JavaType type = mapper.getTypeFactory().constructParametricType(ApiConstructor.class,
                    mapper.getTypeFactory().constructCollectionType(List.class, WebServiceResponse.class));

            ApiConstructor<List<WebServiceResponse>> apiResponse = mapper.readValue(jsonResponse, type);

// Truy xuất dữ liệu từ apiResponse
            String action = apiResponse.getAction();
            if (Objects.equals(action, "get all webservices")) {
                List<WebServiceResponse> webServices = apiResponse.getMessage();
                DefaultTableModel model = (DefaultTableModel) tbWebService.getModel();
                model.setRowCount(0);
                for (WebServiceResponse webService : webServices) {
                    model.addRow(new Object[]{
                            webService.getServiceName(),
                            webService.getStatus(),
                            webService.getIPHost(),
                            webService.getPort(),
                            webService.getSubDomain(),
                            webService.getUsername(),
                    });
                }
            }
        } catch (IOException e) {
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnNewWebService = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbWebService = new javax.swing.JTable();
        btnActive = new javax.swing.JButton();
        lbUsername = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }

            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnNewWebService.setText("New webservice");
        btnNewWebService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewWebServiceActionPerformed(evt);
            }
        });

        tbWebService.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Service Name", "Status", "IP Host", "Port", "Subdomain"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tbWebService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbWebServiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbWebService);

        btnActive.setText("Active");
        btnActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActiveActionPerformed(evt);
            }
        });

        lbUsername.setText("Truong Cong Ly");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnNewWebService)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnActive, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16)
                                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnNewWebService, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnActive, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btnStopActionPerformed(ActionEvent evt) {
        if (!Objects.equals(subDomain, "")) {
            if(!Objects.equals(status, "Stopped")){
                ApiConstructor<StopRequest> apiConstructor = new ApiConstructor<>("stop webservice", new StopRequest(subDomain));

                try {
//            Chuyển đổi sang JSON
                    ObjectMapper mapper = new ObjectMapper();
                    String jsonRequest = mapper.writeValueAsString(apiConstructor);
                    client.getOut().write(jsonRequest.getBytes(StandardCharsets.UTF_8));
                    client.getOut().flush();

//            RESPONSE
                    byte[] buffer = new byte[1024];
                    int bytesRead = client.getIn().read(buffer);
                    String jsonResponse = new String(buffer, 0, bytesRead, StandardCharsets.UTF_8);
//            JSON => Text
                    JsonNode rootNode = mapper.readTree(jsonResponse);
                    String message = rootNode.get("message").asText();
                    if(Objects.equals(message, "Success")){
                        // Cập nhật cột "Status" thành "Stopped" trong JTable
                        DefaultTableModel model = (DefaultTableModel) tbWebService.getModel();
                        model.setValueAt("Stopped", selectedRowIndex, 1);  // Cập nhật giá trị cột Status (cột thứ 1) thành "Stopped"
                        JOptionPane.showMessageDialog(this, "Web service has been stopped", "Information", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(null, "Stop failed!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (IOException e){
                    e.printStackTrace();
                }
            }else{
                JOptionPane.showMessageDialog(this, "Your web service is STOPPED", "Information!", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please, choose a web service you want to stop", "Information!", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void btnRefreshActionPerformed(ActionEvent evt) {
        getAllData();
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {
        // TODO add your handling code here:
    }

    private void btnNewWebServiceActionPerformed(java.awt.event.ActionEvent evt) {
        CreateWebServiceGUI newWebServiceGUI = new CreateWebServiceGUI(this, client, username);
        newWebServiceGUI.setVisible(true);
        this.setEnabled(false);
    }

    private void btnActiveActionPerformed(java.awt.event.ActionEvent evt) {
        if (!Objects.equals(subDomain, "")) {
            if(!Objects.equals(status, "Running")){
                ApiConstructor<ActiveRequest> apiConstructor = new ApiConstructor<>("active webservice", new ActiveRequest(subDomain));

                try {
//            Chuyển đổi sang JSON
                    ObjectMapper mapper = new ObjectMapper();
                    String jsonRequest = mapper.writeValueAsString(apiConstructor);
                    client.getOut().write(jsonRequest.getBytes(StandardCharsets.UTF_8));
                    client.getOut().flush();

//            RESPONSE
                    byte[] buffer = new byte[1024];
                    int bytesRead = client.getIn().read(buffer);
                    String jsonResponse = new String(buffer, 0, bytesRead, StandardCharsets.UTF_8);
//            JSON => Text
                    JsonNode rootNode = mapper.readTree(jsonResponse);
                    String message = rootNode.get("message").asText();
                    if(Objects.equals(message, "Success")){
                        // Cập nhật cột "Status" thành "Running" trong JTable
                        DefaultTableModel model = (DefaultTableModel) tbWebService.getModel();
                        model.setValueAt("Running", selectedRowIndex, 1);  // Cập nhật giá trị cột Status (cột thứ 1) thành "Running"
                        JOptionPane.showMessageDialog(this, "Web service has been activated and is now Running", "Information", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(null, "Active failed!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (IOException e){
                    e.printStackTrace();
                }
            }else{
                JOptionPane.showMessageDialog(this, "Your web service is RUNNING", "Information!", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please, choose a web service you want to active", "Information!", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {
        LoginGUI loginGUI = new LoginGUI(client);
        loginGUI.setVisible(true);
        this.dispose();
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        // TODO add your handling code here:
    }

    private void tbWebServiceMouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 1 && tbWebService.getSelectedRow() != -1) {
            DefaultTableModel model = (DefaultTableModel) tbWebService.getModel();
            selectedRowIndex = tbWebService.getSelectedRow();
            subDomain = model.getValueAt(selectedRowIndex, 4).toString();
            status = model.getValueAt(selectedRowIndex, 1).toString();
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnActive;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewWebService;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnStop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JTable tbWebService;
    // End of variables declaration
}